Rails.application.routes.draw do
  
  # Route generated by "rails generate controller users my_portfolio" command
    # get 'users/my_portfolio'
  # End Route generated by "rails generate controller users my_portfolio" command
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
end
